### ISSUE TITLE
How can I run it without fiji?

### ISSUE THREAD

**Issue by zhangliukun** [mpicbg-csbd/stardist-imagej#16]
I have question that wherther I can run this plugin without the fiji? 
when I run mvn clean compile this project,  the error messages are as follows:
Non-resolvable parent POM for de.csbdresden:StarDist_:0.3.0:.........

**Comment by uschmidt83** [comment]
What do you want to do?

**Comment by zhangliukun** [comment]
I want to run it as a independent client.  I get this error when I run mvn compile.

**Comment by uschmidt83** [comment]
But why? E.g.: Do you want to run it headless from the command line? Or do you want to automate/script the GUI?

**Comment by zhangliukun** [comment]
yeah, I want to run it in command line or use my own GUI

**Comment by uschmidt83** [comment]
Then I'd rather suggest you use our Python package: https://github.com/stardist/stardist

**Comment by zhangliukun** [comment]
That's a wonderful work. I just want the postprocess of this plugin stardist-imagej. 
This plugin has some fantastic functions such as count the cells  that the  Python package don't have  and the UI is better.
I will be appreciate that if you could tell me how to realize the effect in this plugin with the python package.

**Comment by zhangliukun** [comment]
And I also have a question that whether the plugin and the python package are different in the preprocess or some details?
I tried both the python package and this plugin with the same model "models/2D/he_heavy_augment.zip" with the same threshold and nms, but the results between them have little defference. Most of them are same. I wonder what is the difference that leads to it.

**Comment by uschmidt83** [comment]
> I will be appreciate that if you could tell me how to realize the effect in this plugin with the python package.

I don't understand what you want to do.

**Comment by uschmidt83** [comment]
> but the results between them have little defference. Most of them are same. I wonder what is the difference that leads to it.

I'm not fully sure, but the model could be slightly different. But it can also be due to minor differences between Fiji and Python and/or the computing device (CPU/GPU).

**Comment by ctrueden** [comment]
@zhangliukun wrote:
> wherther I can run this plugin without the fiji?

One option is to use [PyImageJ](https://pyimagej.readthedocs.org/) with `imagej.init("net.imagej:imagej+de.csbdresden:StarDist_")` and then invoking the plugin [via `ij.py.run_plugin`](https://pyimagej.readthedocs.io/en/latest/7-Running-Macros-Scripts-and-Plugins.html#example-run-a-plugin-ij-py-run-plugin). It's more convoluted than calling stardist in Python directly, but will go through the Java plugin's functionality.
