### ISSUE TITLE
The training process of he_heavy_augment model

### ISSUE THREAD

**Issue by ShangWeiKuo** [mpicbg-csbd/stardist-imagej#18]
Hello,

Will there be a .ipynb file concerned with the training process of he_heavy_augment model ?

Besides. What are the differences in training process between **dsb2018_heavy_augment** and **he_heavy_augment** model ?

**Comment by uschmidt83** [comment]
Hi @ShangWeiKuo,

I don't understand why you're opening an issue about these topics in the `stardist-imagej` repo. Please ask these general questions at the image.sc forum.
