### ISSUE TITLE
Stardist in Fiji not launching

### ISSUE THREAD

**Issue by josdmz** [mpicbg-csbd/stardist-imagej#19]
Hello,
I am trying to use stardist in Fiji as I have before and I keep getting an error saying tensorflow could not load. I have tried selecting each of the available options in the pop up Tensorflow version managment menu but I can not get past this error. I have tried following advice from this post (https://forum.image.sc/t/stardist-fiji-plugin-not-launching-correctly/37013) and could not resolve. Please see my post here (https://forum.image.sc/t/tensorflow-error-when-trying-to-use-stardist2d-in-fiji/76644) for images. Is there any way you can help me overcome this issue and use the stardist 2D? Thank you

**Comment by uschmidt83** [comment]
I replied to you [at the forum](https://forum.image.sc/t/tensorflow-error-when-trying-to-use-stardist2d-in-fiji/76644). By the way, we get notified about all forum posts that use the tag `stardist`.
